##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: cred-autenticacion-svc
  devtools:
    add-properties: false
  profiles:
    include:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cred_autenticacion
    username: postgres
    password: admin
  sql.init.mode: never

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "cred_autenticacion"
    schema: "public"
    username: "postgres"
    password: "admin"