server:
  port: ${SERVER_PORT_AUTH:8080}
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  webflux:
    base-path: /auth
  application:
    name: ${APP_NAME_AUTH:cred-autenticacion-svc}
  devtools:
    add-properties: false
  jackson:
    parser:
      STRICT_DUPLICATE_DETECTION: true
  profiles:
    include: ${SPRING_PROFILES_INCLUDE:}
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:admin}
  sql.init.mode: "never"
  messages:
    basename: ${I18N_BASENAME_AUTH:i18n/validation-messages}
    encoding: ${I18N_ENCODING_AUTH:UTF-8}
    fallback-to-system-locale: false

adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:pragma_credi}
    schema: ${DB_SCHEMA:public}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

logging:
  level:
    co.com.pragma.autenticacion.api: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod}
    ttl-seconds: ${JWT_TTL_SECONDS:3600}