server:
  port: 8080
spring:
  application:
    name: "cred-autenticacion-svc"
  devtools:
    add-properties: false
  profiles:
    include: null
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/cred_autenticacion"
    username: "postgres"
    password: "admin"
  sql.init.mode: "never"
  messages:
    basename: i18n/validation-messages
    encoding: UTF-8
    fallback-to-system-locale: false

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "cred_autenticacion"
    schema: "public"
    username: "postgres"
    password: "admin"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
